In [1]:
import cv2
import numpy as np
import pandas as pd

In [2]:
# Load the image
image = cv2.imread('lane_image.jpg')

# Iteration 1

In [3]:
# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [4]:
# Apply Gaussian blur to reduce noise
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

In [5]:
# Perform Canny edge detection
edges = cv2.Canny(blurred, 50, 150)

In [6]:
# Find the contours of the edges
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

In [7]:
# Initialize variables to hold the leftmost and rightmost points
leftmost = None
rightmost = None

In [8]:
# Iterate through contours and find the extreme leftmost and rightmost points
for contour in contours:
    # Get extreme points for each contour
    left_point = tuple(contour[contour[:, :, 0].argmin()][0])
    right_point = tuple(contour[contour[:, :, 0].argmax()][0])
    
    # Update the leftmost and rightmost points for the road boundary
    if leftmost is None or left_point[0] < leftmost[0]:
        leftmost = left_point
    if rightmost is None or right_point[0] > rightmost[0]:
        rightmost = right_point

In [9]:
# Calculate the road width in pixels (distance between the leftmost and rightmost points)
road_width_pixels = np.linalg.norm(np.array(leftmost) - np.array(rightmost))

In [10]:
# Conversion from Pixels to Meters using the black car's width (assuming 1.5 meters for a nearby black taxi)
car_width_meters = 1.5  # Estimated width of the black car in meters
car_width_pixels = 150  # Approximate car width in pixels (adjust as necessary)

In [11]:
# Calculate the pixel-to-meter ratio
pixels_per_meter = car_width_pixels / car_width_meters

In [12]:
# Calculate the road width in meters
road_width_meters = road_width_pixels / pixels_per_meter

In [13]:
# Convert road width to feet
road_width_feet = road_width_meters * 3.28084

In [14]:
# Draw the detected leftmost and rightmost road boundaries
road_image = image.copy()
cv2.circle(road_image, leftmost, 10, (0, 255, 0), -1)  # Leftmost point
cv2.circle(road_image, rightmost, 10, (0, 255, 0), -1)  # Rightmost point

array([[[131, 142, 146],
        [138, 145, 148],
        [145, 146, 150],
        ...,
        [ 84,  93,  90],
        [ 74,  83,  80],
        [ 63,  72,  69]],

       [[128, 139, 143],
        [139, 145, 150],
        [146, 147, 151],
        ...,
        [ 94, 103, 100],
        [ 91, 100,  97],
        [ 80,  89,  86]],

       [[130, 140, 147],
        [142, 148, 153],
        [148, 147, 151],
        ...,
        [ 94, 101,  98],
        [100, 107, 104],
        [ 93, 100,  97]],

       ...,

       [[ 72,  83, 113],
        [ 76,  87, 117],
        [ 89, 100, 128],
        ...,
        [ 76,  78,  79],
        [ 68,  69,  73],
        [ 69,  70,  74]],

       [[ 77,  88, 118],
        [ 75,  86, 116],
        [ 83,  94, 122],
        ...,
        [ 76,  78,  79],
        [ 71,  72,  76],
        [ 66,  67,  71]],

       [[ 78,  89, 119],
        [ 72,  83, 113],
        [ 74,  85, 113],
        ...,
        [ 66,  68,  69],
        [ 78,  79,  83],
        [ 82,  83,  87]]

In [15]:
# Draw a line between the leftmost and rightmost points (representing road width)
cv2.line(road_image, leftmost, rightmost, (255, 0, 0), 2)

array([[[131, 142, 146],
        [138, 145, 148],
        [145, 146, 150],
        ...,
        [ 84,  93,  90],
        [ 74,  83,  80],
        [ 63,  72,  69]],

       [[128, 139, 143],
        [139, 145, 150],
        [146, 147, 151],
        ...,
        [ 94, 103, 100],
        [ 91, 100,  97],
        [ 80,  89,  86]],

       [[130, 140, 147],
        [142, 148, 153],
        [148, 147, 151],
        ...,
        [ 94, 101,  98],
        [100, 107, 104],
        [ 93, 100,  97]],

       ...,

       [[ 72,  83, 113],
        [ 76,  87, 117],
        [ 89, 100, 128],
        ...,
        [ 76,  78,  79],
        [ 68,  69,  73],
        [ 69,  70,  74]],

       [[ 77,  88, 118],
        [ 75,  86, 116],
        [ 83,  94, 122],
        ...,
        [ 76,  78,  79],
        [ 71,  72,  76],
        [ 66,  67,  71]],

       [[ 78,  89, 119],
        [ 72,  83, 113],
        [ 74,  85, 113],
        ...,
        [ 66,  68,  69],
        [ 78,  79,  83],
        [ 82,  83,  87]]

In [16]:
# Add text annotation showing the road width in feet
font = cv2.FONT_HERSHEY_SIMPLEX
text = f"Lane Width: {road_width_feet:.2f} ft"
cv2.putText(road_image, text, (int((leftmost[0] + rightmost[0]) / 2), leftmost[1] - 10), font, 0.7, (255, 0, 0), 2, cv2.LINE_AA)

array([[[131, 142, 146],
        [138, 145, 148],
        [145, 146, 150],
        ...,
        [ 84,  93,  90],
        [ 74,  83,  80],
        [ 63,  72,  69]],

       [[128, 139, 143],
        [139, 145, 150],
        [146, 147, 151],
        ...,
        [ 94, 103, 100],
        [ 91, 100,  97],
        [ 80,  89,  86]],

       [[130, 140, 147],
        [142, 148, 153],
        [148, 147, 151],
        ...,
        [ 94, 101,  98],
        [100, 107, 104],
        [ 93, 100,  97]],

       ...,

       [[ 72,  83, 113],
        [ 76,  87, 117],
        [ 89, 100, 128],
        ...,
        [ 76,  78,  79],
        [ 68,  69,  73],
        [ 69,  70,  74]],

       [[ 77,  88, 118],
        [ 75,  86, 116],
        [ 83,  94, 122],
        ...,
        [ 76,  78,  79],
        [ 71,  72,  76],
        [ 66,  67,  71]],

       [[ 78,  89, 119],
        [ 72,  83, 113],
        [ 74,  85, 113],
        ...,
        [ 66,  68,  69],
        [ 78,  79,  83],
        [ 82,  83,  87]]

In [20]:
# Display the final image with the correct annotation
cv2.imshow("Lane Width in Feet", road_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# Print the calculated width for reference
print(f"Lane width in pixels: {road_width_pixels:.2f} pixels")
print(f"Lane width in meters: {road_width_meters:.2f} meters")
print(f"Lane width in feet: {road_width_feet:.2f} feet")

Road width in pixels: 639.41 pixels
Road width in meters: 6.39 meters
Road width in feet: 20.98 feet
